export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER';
export const UPDATE_NEW_CUSTOMER_FIELD = 'UPDATE_NEW_CUSTOMER_FIELD';

export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
export const UPDATE_NEW_ORDER_FIELD = 'UPDATE_NEW_ORDER_FIELD';
