export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER';
export const UPDATE_NEW_CUSTOMER_FIELD = 'UPDATE_NEW_CUSTOMER_FIELD';
export const ADD_CUSTOMER_VALIDATION_ERROR_OCCURRED = 'ADD_CUSTOMER_VALIDATION_ERROR_OCCURRED';

export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
export const UPDATE_NEW_ORDER_FIELD = 'UPDATE_NEW_ORDER_FIELD';

export const GET_CUSTOMER_API_REQUEST_START = 'GET_CUSTOMER_API_REQUEST_START';
export const GET_CUSTOMER_API_REQUEST_SUCCESS = 'GET_CUSTOMER_API_REQUEST_SUCCESS';
export const GET_CUSTOMER_API_REQUEST_ERROR = 'GET_CUSTOMER_API_REQUEST_ERROR';

export const ADD_NEW_CUSTOMER_API_REQUEST_START = 'ADD_NEW_CUSTOMER_API_REQUEST_START';
export const ADD_NEW_CUSTOMER_API_REQUEST_SUCCESS = 'ADD_NEW_CUSTOMER_API_REQUEST_SUCCESS';
export const ADD_NEW_CUSTOMER_API_REQUEST_ERROR = 'ADD_NEW_CUSTOMER_API_REQUEST_ERROR';
